// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: expense.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddExpenseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                               // req
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`                         // req
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`                       // req
	Note          string                 `protobuf:"bytes,4,opt,name=note,proto3" json:"note,omitempty"`                               // opt
	OccurredAt    string                 `protobuf:"bytes,5,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"` // opt
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddExpenseRequest) Reset() {
	*x = AddExpenseRequest{}
	mi := &file_expense_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddExpenseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddExpenseRequest) ProtoMessage() {}

func (x *AddExpenseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_expense_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddExpenseRequest.ProtoReflect.Descriptor instead.
func (*AddExpenseRequest) Descriptor() ([]byte, []int) {
	return file_expense_proto_rawDescGZIP(), []int{0}
}

func (x *AddExpenseRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddExpenseRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *AddExpenseRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *AddExpenseRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *AddExpenseRequest) GetOccurredAt() string {
	if x != nil {
		return x.OccurredAt
	}
	return ""
}

type AddExpenseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddExpenseResponse) Reset() {
	*x = AddExpenseResponse{}
	mi := &file_expense_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddExpenseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddExpenseResponse) ProtoMessage() {}

func (x *AddExpenseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_expense_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddExpenseResponse.ProtoReflect.Descriptor instead.
func (*AddExpenseResponse) Descriptor() ([]byte, []int) {
	return file_expense_proto_rawDescGZIP(), []int{1}
}

func (x *AddExpenseResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AddExpenseResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListExpensesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExpensesRequest) Reset() {
	*x = ListExpensesRequest{}
	mi := &file_expense_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExpensesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExpensesRequest) ProtoMessage() {}

func (x *ListExpensesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_expense_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExpensesRequest.ProtoReflect.Descriptor instead.
func (*ListExpensesRequest) Descriptor() ([]byte, []int) {
	return file_expense_proto_rawDescGZIP(), []int{2}
}

func (x *ListExpensesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListExpensesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type Expense struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Note          string                 `protobuf:"bytes,5,opt,name=note,proto3" json:"note,omitempty"`
	OccurredAt    string                 `protobuf:"bytes,6,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Expense) Reset() {
	*x = Expense{}
	mi := &file_expense_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Expense) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Expense) ProtoMessage() {}

func (x *Expense) ProtoReflect() protoreflect.Message {
	mi := &file_expense_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Expense.ProtoReflect.Descriptor instead.
func (*Expense) Descriptor() ([]byte, []int) {
	return file_expense_proto_rawDescGZIP(), []int{3}
}

func (x *Expense) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Expense) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Expense) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Expense) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Expense) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *Expense) GetOccurredAt() string {
	if x != nil {
		return x.OccurredAt
	}
	return ""
}

func (x *Expense) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ListExpensesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expenses      []*Expense             `protobuf:"bytes,1,rep,name=expenses,proto3" json:"expenses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExpensesResponse) Reset() {
	*x = ListExpensesResponse{}
	mi := &file_expense_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExpensesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExpensesResponse) ProtoMessage() {}

func (x *ListExpensesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_expense_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExpensesResponse.ProtoReflect.Descriptor instead.
func (*ListExpensesResponse) Descriptor() ([]byte, []int) {
	return file_expense_proto_rawDescGZIP(), []int{4}
}

func (x *ListExpensesResponse) GetExpenses() []*Expense {
	if x != nil {
		return x.Expenses
	}
	return nil
}

type SummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummaryRequest) Reset() {
	*x = SummaryRequest{}
	mi := &file_expense_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummaryRequest) ProtoMessage() {}

func (x *SummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_expense_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummaryRequest.ProtoReflect.Descriptor instead.
func (*SummaryRequest) Descriptor() ([]byte, []int) {
	return file_expense_proto_rawDescGZIP(), []int{5}
}

func (x *SummaryRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *SummaryRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type CategorySummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Items         int32                  `protobuf:"varint,2,opt,name=items,proto3" json:"items,omitempty"`
	Total         float64                `protobuf:"fixed64,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategorySummary) Reset() {
	*x = CategorySummary{}
	mi := &file_expense_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategorySummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategorySummary) ProtoMessage() {}

func (x *CategorySummary) ProtoReflect() protoreflect.Message {
	mi := &file_expense_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategorySummary.ProtoReflect.Descriptor instead.
func (*CategorySummary) Descriptor() ([]byte, []int) {
	return file_expense_proto_rawDescGZIP(), []int{6}
}

func (x *CategorySummary) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CategorySummary) GetItems() int32 {
	if x != nil {
		return x.Items
	}
	return 0
}

func (x *CategorySummary) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type SummaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summaries     []*CategorySummary     `protobuf:"bytes,1,rep,name=summaries,proto3" json:"summaries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummaryResponse) Reset() {
	*x = SummaryResponse{}
	mi := &file_expense_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummaryResponse) ProtoMessage() {}

func (x *SummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_expense_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummaryResponse.ProtoReflect.Descriptor instead.
func (*SummaryResponse) Descriptor() ([]byte, []int) {
	return file_expense_proto_rawDescGZIP(), []int{7}
}

func (x *SummaryResponse) GetSummaries() []*CategorySummary {
	if x != nil {
		return x.Summaries
	}
	return nil
}

var File_expense_proto protoreflect.FileDescriptor

const file_expense_proto_rawDesc = "" +
	"\n" +
	"\rexpense.proto\x12\n" +
	"expense.v1\x1a\x1cgoogle/api/annotations.proto\"\x90\x01\n" +
	"\x11AddExpenseRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x12\n" +
	"\x04note\x18\x04 \x01(\tR\x04note\x12\x1f\n" +
	"\voccurred_at\x18\x05 \x01(\tR\n" +
	"occurredAt\"<\n" +
	"\x12AddExpenseResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"C\n" +
	"\x13ListExpensesRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"\xb5\x01\n" +
	"\aExpense\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x12\n" +
	"\x04note\x18\x05 \x01(\tR\x04note\x12\x1f\n" +
	"\voccurred_at\x18\x06 \x01(\tR\n" +
	"occurredAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\"G\n" +
	"\x14ListExpensesResponse\x12/\n" +
	"\bexpenses\x18\x01 \x03(\v2\x13.expense.v1.ExpenseR\bexpenses\"4\n" +
	"\x0eSummaryRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\"Y\n" +
	"\x0fCategorySummary\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12\x14\n" +
	"\x05items\x18\x02 \x01(\x05R\x05items\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x01R\x05total\"L\n" +
	"\x0fSummaryResponse\x129\n" +
	"\tsummaries\x18\x01 \x03(\v2\x1b.expense.v1.CategorySummaryR\tsummaries2\xbb\x02\n" +
	"\x0eExpenseService\x12d\n" +
	"\n" +
	"AddExpense\x12\x1d.expense.v1.AddExpenseRequest\x1a\x1e.expense.v1.AddExpenseResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/expenses\x12g\n" +
	"\fListExpenses\x12\x1f.expense.v1.ListExpensesRequest\x1a .expense.v1.ListExpensesResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/v1/expenses\x12Z\n" +
	"\n" +
	"GetSummary\x12\x1a.expense.v1.SummaryRequest\x1a\x1b.expense.v1.SummaryResponse\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/v1/summaryB3Z1github.com/digitlock/expense-demo/proto;expensev1b\x06proto3"

var (
	file_expense_proto_rawDescOnce sync.Once
	file_expense_proto_rawDescData []byte
)

func file_expense_proto_rawDescGZIP() []byte {
	file_expense_proto_rawDescOnce.Do(func() {
		file_expense_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_expense_proto_rawDesc), len(file_expense_proto_rawDesc)))
	})
	return file_expense_proto_rawDescData
}

var file_expense_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_expense_proto_goTypes = []any{
	(*AddExpenseRequest)(nil),    // 0: expense.v1.AddExpenseRequest
	(*AddExpenseResponse)(nil),   // 1: expense.v1.AddExpenseResponse
	(*ListExpensesRequest)(nil),  // 2: expense.v1.ListExpensesRequest
	(*Expense)(nil),              // 3: expense.v1.Expense
	(*ListExpensesResponse)(nil), // 4: expense.v1.ListExpensesResponse
	(*SummaryRequest)(nil),       // 5: expense.v1.SummaryRequest
	(*CategorySummary)(nil),      // 6: expense.v1.CategorySummary
	(*SummaryResponse)(nil),      // 7: expense.v1.SummaryResponse
}
var file_expense_proto_depIdxs = []int32{
	3, // 0: expense.v1.ListExpensesResponse.expenses:type_name -> expense.v1.Expense
	6, // 1: expense.v1.SummaryResponse.summaries:type_name -> expense.v1.CategorySummary
	0, // 2: expense.v1.ExpenseService.AddExpense:input_type -> expense.v1.AddExpenseRequest
	2, // 3: expense.v1.ExpenseService.ListExpenses:input_type -> expense.v1.ListExpensesRequest
	5, // 4: expense.v1.ExpenseService.GetSummary:input_type -> expense.v1.SummaryRequest
	1, // 5: expense.v1.ExpenseService.AddExpense:output_type -> expense.v1.AddExpenseResponse
	4, // 6: expense.v1.ExpenseService.ListExpenses:output_type -> expense.v1.ListExpensesResponse
	7, // 7: expense.v1.ExpenseService.GetSummary:output_type -> expense.v1.SummaryResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_expense_proto_init() }
func file_expense_proto_init() {
	if File_expense_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_expense_proto_rawDesc), len(file_expense_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_expense_proto_goTypes,
		DependencyIndexes: file_expense_proto_depIdxs,
		MessageInfos:      file_expense_proto_msgTypes,
	}.Build()
	File_expense_proto = out.File
	file_expense_proto_goTypes = nil
	file_expense_proto_depIdxs = nil
}
